<template>
  <div class="poem-nav">
    <a
      v-if="prevPoem"
      :href="prevLink"
      class="prev-poem"
    >
      <span class="nav-label">← 上一篇</span>
      <span class="nav-title">{{ prevPoem.title }}</span>
    </a>
    <span v-else class="nav-placeholder"></span>

    <a
      v-if="nextPoem"
      :href="nextLink"
      class="next-poem"
    >
      <span class="nav-label">下一篇 →</span>
      <span class="nav-title">{{ nextPoem.title }}</span>
    </a>
    <span v-else class="nav-placeholder"></span>
  </div>
</template>

<script setup>
import { computed, ref, onMounted } from 'vue'

const poemLists = {
  tangshi: [
    { id: 1, title: '静夜思' },
    { id: 2, title: '春晓' },
    { id: 3, title: '登鹳雀楼' },
    { id: 4, title: '相思' },
    { id: 5, title: '江雪' },
    { id: 6, title: '春望' },
    { id: 7, title: '望庐山瀑布' },
    { id: 8, title: '早发白帝城' },
    { id: 9, title: '枫桥夜泊' },
    { id: 10, title: '出塞' },
    { id: 11, title: '凉州词' },
    { id: 12, title: '送元二使安西' },
    { id: 13, title: '登幽州台歌' },
    { id: 14, title: '悯农' },
    { id: 15, title: '游子吟' },
    { id: 16, title: '过故人庄' },
    { id: 17, title: '山居秋暝' },
    { id: 18, title: '使至塞上' },
    { id: 19, title: '送杜少府之任蜀州' },
    { id: 20, title: '黄鹤楼' },
    { id: 21, title: '别董大' },
    { id: 22, title: '绝句' },
    { id: 23, title: '望岳' },
    { id: 24, title: '登高' },
    { id: 25, title: '琵琶行' },
    { id: 26, title: '长恨歌' },
    { id: 27, title: '将进酒' },
    { id: 28, title: '行路难' },
    { id: 29, title: '月下独酌' },
    { id: 30, title: '夜雨寄北' },
    { id: 31, title: '无题' },
    { id: 32, title: '锦瑟' },
    { id: 33, title: '登鹳雀楼' },
    { id: 34, title: '相思' },
    { id: 35, title: '江雪' },
    { id: 36, title: '乌衣巷' },
    { id: 37, title: '竹枝词' },
    { id: 38, title: '枫桥夜泊' },
    { id: 39, title: '早发白帝城' },
    { id: 40, title: '望庐山瀑布' },
    { id: 41, title: '逢入京使' },
    { id: 42, title: '夜上受降城闻笛' },
    { id: 43, title: '寒食' },
    { id: 44, title: '滁州西涧' },
    { id: 45, title: '赋得古原草送别' },
    { id: 46, title: '池上' },
    { id: 47, title: '忆江南' },
    { id: 48, title: '钱塘湖春行' },
    { id: 49, title: '山行' },
    { id: 50, title: '清明' },
    { id: 51, title: '登鹳雀楼' },
    { id: 52, title: '凉州词' },
    { id: 53, title: '出塞' },
    { id: 54, title: '芙蓉楼送辛渐' },
    { id: 55, title: '鹿柴' },
    { id: 56, title: '竹里馆' },
    { id: 57, title: '送元二使安西' },
    { id: 58, title: '九月九日忆山东兄弟' },
    { id: 59, title: '相思' },
    { id: 60, title: '杂诗' },
    { id: 61, title: '终南山' },
    { id: 62, title: '过故人庄' },
    { id: 63, title: '春晓' },
    { id: 64, title: '宿建德江' },
    { id: 65, title: '岁暮归南山' },
    { id: 66, title: '与诸子登岘山' },
    { id: 67, title: '凉州词' },
    { id: 68, title: '别董大' },
    { id: 69, title: '塞上听吹笛' },
    { id: 70, title: '白雪歌送武判官归京' },
    { id: 71, title: '走马川行奉送封大夫出师西征' },
    { id: 72, title: '石壕吏' },
    { id: 73, title: '新婚别' },
    { id: 74, title: '垂老别' },
    { id: 75, title: '蜀相' },
    { id: 76, title: '客至' },
    { id: 77, title: '春夜喜雨' },
    { id: 78, title: '登高' },
    { id: 79, title: '登岳阳楼' },
    { id: 80, title: '秋兴八首·其一' },
    { id: 81, title: '咏怀古迹·其三' },
    { id: 82, title: '阁夜' },
    { id: 83, title: '江汉' },
    { id: 84, title: '旅夜书怀' },
    { id: 85, title: '望岳' },
    { id: 86, title: '赠花卿' },
    { id: 87, title: '绝句' },
    { id: 88, title: '枫桥夜泊' },
    { id: 89, title: '滁州西涧' },
    { id: 90, title: '游子吟' },
    { id: 91, title: '登科后' },
    { id: 92, title: '题都城南庄' },
    { id: 93, title: '秋思' },
    { id: 94, title: '十五夜望月' },
    { id: 95, title: '石头城' },
    { id: 96, title: '乌衣巷' },
    { id: 97, title: '竹枝词' },
    { id: 98, title: '秋词' },
    { id: 99, title: '悯农·其一' },
    { id: 100, title: '悯农·其二' }
  ],
  songci: [
    { id: 1, title: '水调歌头·明月几时有' },
    { id: 2, title: '念奴娇·赤壁怀古' },
    { id: 3, title: '声声慢·寻寻觅觅' },
    { id: 4, title: '如梦令·昨夜雨疏风骤' },
    { id: 5, title: '虞美人·春花秋月何时了' },
    { id: 6, title: '雨霖铃·寒蝉凄切' },
    { id: 7, title: '青玉案·元夕' },
    { id: 8, title: '一剪梅·红藕香残玉簟秋' },
    { id: 9, title: '破阵子·为陈同甫赋壮词以寄之' },
    { id: 10, title: '江城子·密州出猎' },
    { id: 11, title: '满江红·写怀' },
    { id: 12, title: '卜算子·咏梅' },
    { id: 13, title: '永遇乐·京口北固亭怀古' },
    { id: 14, title: '蝶恋花·伫倚危楼风细细' },
    { id: 15, title: '浣溪沙·一曲新词酒一杯' },
    { id: 16, title: '鹊桥仙·纤云弄巧' },
    { id: 17, title: '苏幕遮·怀旧' },
    { id: 18, title: '西江月·夜行黄沙道中' },
    { id: 19, title: '定风波·莫听穿林打叶声' },
    { id: 20, title: '醉花阴·薄雾浓云愁永昼' },
    { id: 21, title: '渔家傲·秋思' },
    { id: 22, title: '扬州慢·淮左名都' },
    { id: 23, title: '念奴娇·过洞庭' },
    { id: 24, title: '贺新郎·甚矣吾衰矣' },
    { id: 25, title: '兰陵王·柳' },
    { id: 26, title: '踏莎行·郴州旅舍' },
    { id: 27, title: '江城子·乙卯正月二十日夜记梦' },
    { id: 28, title: '蝶恋花·花褪残红青杏小' },
    { id: 29, title: '如梦令·常记溪亭日暮' },
    { id: 30, title: '一剪梅·舟过吴江' },
    { id: 31, title: '虞美人·听雨' },
    { id: 32, title: '青玉案·元夕' },
    { id: 33, title: '鹧鸪天·代人赋' },
    { id: 34, title: '声声慢·寻寻觅觅' },
    { id: 35, title: '水龙吟·登建康赏心亭' },
    { id: 36, title: '念奴娇·过洞庭' },
    { id: 37, title: '八声甘州·对潇潇暮雨洒江天' },
    { id: 38, title: '桂枝香·金陵怀古' },
    { id: 39, title: '浣溪沙·游蕲水清泉寺' },
    { id: 40, title: '临江仙·夜归临皋' },
    { id: 41, title: '卜算子·黄州定慧院寓居作' },
    { id: 42, title: '鹊桥仙·七夕' },
    { id: 43, title: '钗头凤·红酥手' },
    { id: 44, title: '诉衷情·当年万里觅封侯' },
    { id: 45, title: '破阵子·春景' },
    { id: 46, title: '天仙子·水调数声持酒听' },
    { id: 47, title: '水龙吟·次韵章质夫杨花词' },
    { id: 48, title: '青玉案·元夕' },
    { id: 49, title: '武陵春·春晚' },
    { id: 50, title: '卜算子·我住长江头' },
    { id: 51, title: '苏幕遮·怀旧' },
    { id: 52, title: '渔家傲·秋思' },
    { id: 53, title: '御街行·秋日怀旧' },
    { id: 54, title: '天仙子·水调数声持酒听' },
    { id: 55, title: '青门引·春思' },
    { id: 56, title: '浣溪沙·一曲新词酒一杯' },
    { id: 57, title: '浣溪沙·一向年光有限身' },
    { id: 58, title: '蝶恋花·槛菊愁烟兰泣露' },
    { id: 59, title: '破阵子·春景' },
    { id: 60, title: '踏莎行·祖席离歌' },
    { id: 61, title: '玉楼春·春恨' },
    { id: 62, title: '采桑子·群芳过后西湖好' },
    { id: 63, title: '踏莎行·候馆梅残' },
    { id: 64, title: '生查子·元夕' },
    { id: 65, title: '玉楼春·尊前拟把归期说' },
    { id: 66, title: '浪淘沙令·帘外雨潺潺' },
    { id: 67, title: '相见欢·林花谢了春红' },
    { id: 68, title: '清平乐·别来春半' },
    { id: 69, title: '蝶恋花·庭院深深深几许' },
    { id: 70, title: '临江仙·柳外轻雷池上雨' },
    { id: 71, title: '桂枝香·金陵怀古' },
    { id: 72, title: '千秋岁引·秋景' },
    { id: 73, title: '鹧鸪天·彩袖殷勤捧玉钟' },
    { id: 74, title: '临江仙·梦后楼台高锁' },
    { id: 75, title: '蝶恋花·醉别西楼醒不记' },
    { id: 76, title: '鹧鸪天·醉拍春衫惜旧香' },
    { id: 77, title: '清平乐·留人不住' },
    { id: 78, title: '木兰花·秋千院落重帘暮' },
    { id: 79, title: '虞美人·有美堂赠述古' },
    { id: 80, title: '南乡子·送述古' },
    { id: 81, title: '蝶恋花·记得画屏初会遇' },
    { id: 82, title: '少年游·润州作' },
    { id: 83, title: '定风波·莫听穿林打叶声' },
    { id: 84, title: '江城子·密州出猎' },
    { id: 85, title: '江城子·乙卯正月二十日夜记梦' },
    { id: 86, title: '卜算子·我住长江头' },
    { id: 87, title: '瑞龙吟·大石春景' },
    { id: 88, title: '满庭芳·夏日溧水无想山作' },
    { id: 89, title: '苏幕遮·燎沉香' },
    { id: 90, title: '六丑·落花' },
    { id: 91, title: '兰陵王·柳' },
    { id: 92, title: '西河·金陵怀古' },
    { id: 93, title: '如梦令·常记溪亭日暮' },
    { id: 94, title: '如梦令·昨夜雨疏风骤' },
    { id: 95, title: '一剪梅·红藕香残玉簟秋' },
    { id: 96, title: '醉花阴·薄雾浓云愁永昼' },
    { id: 97, title: '声声慢·寻寻觅觅' },
    { id: 98, title: '永遇乐·落日熔金' },
    { id: 99, title: '武陵春·春晚' },
    { id: 100, title: '渔家傲·天接云涛连晓雾' }
  ],
  yuanqu: [
    { id: 1, title: '天净沙·秋思' },
    { id: 2, title: '山坡羊·潼关怀古' },
    { id: 3, title: '天净沙·秋' },
    { id: 4, title: '四块玉·别情' },
    { id: 5, title: '沉醉东风·渔夫' },
    { id: 6, title: '大德歌·春' },
    { id: 7, title: '寿阳曲·远浦帆归' },
    { id: 8, title: '蟾宫曲·春情' },
    { id: 9, title: '山坡羊·骊山怀古' },
    { id: 10, title: '清江引·秋怀' },
    { id: 11, title: '殿前欢·对菊自叹' },
    { id: 12, title: '水仙子·咏江南' },
    { id: 13, title: '折桂令·春情' },
    { id: 14, title: '人月圆·山中书事' },
    { id: 15, title: '拨不断·叹寒儒' },
    { id: 16, title: '落梅风·人初静' },
    { id: 17, title: '塞鸿秋·浔阳即景' },
    { id: 18, title: '卖花声·怀古' },
    { id: 19, title: '凭阑人·寄征衣' },
    { id: 20, title: '折桂令·叹世' },
    { id: 21, title: '水仙子·夜雨' },
    { id: 22, title: '普天乐·西山夕照' },
    { id: 23, title: '天净沙·春' },
    { id: 24, title: '天净沙·夏' },
    { id: 25, title: '天净沙·冬' },
    { id: 26, title: '沉醉东风·秋景' },
    { id: 27, title: '寿阳曲·潇湘夜雨' },
    { id: 28, title: '寿阳曲·烟寺晚钟' },
    { id: 29, title: '拨不断·菊花开' },
    { id: 30, title: '清江引·秋居' },
    { id: 31, title: '殿前欢·懒云窝' },
    { id: 32, title: '水仙子·寻梅' },
    { id: 33, title: '山坡羊·未央怀古' },
    { id: 34, title: '折桂令·客窗清明' },
    { id: 35, title: '水仙子·重观瀑布' },
    { id: 36, title: '殿前欢·吊古' },
    { id: 37, title: '一半儿·春醉' },
    { id: 38, title: '叨叨令·道情' },
    { id: 39, title: '寄生草·饮' },
    { id: 40, title: '沉醉东风·闲居' },
    { id: 41, title: '寿阳曲·远浦帆归' },
    { id: 42, title: '山坡羊·骊山怀古' },
    { id: 43, title: '驻马听·吹' },
    { id: 44, title: '四块玉·闲适' },
    { id: 45, title: '庆东原·即景' },
    { id: 46, title: '小桃红·春' },
    { id: 47, title: '凭栏人·湖上' },
    { id: 48, title: '卖花声·客况' },
    { id: 49, title: '红绣鞋·天台瀑布寺' },
    { id: 50, title: '蟾宫曲·醉赠乐府' },
    { id: 51, title: '天净沙·秋' },
    { id: 52, title: '天净沙·春' },
    { id: 53, title: '天净沙·夏' },
    { id: 54, title: '天净沙·冬' },
    { id: 55, title: '沉醉东风·渔夫' },
    { id: 56, title: '驻马听·舞' },
    { id: 57, title: '驻马听·歌' },
    { id: 58, title: '庆东原·叹世' },
    { id: 59, title: '水仙子·和卢疏斋西湖' },
    { id: 60, title: '落梅风·远浦秋帆' },
    { id: 61, title: '落梅风·潇湘夜雨' },
    { id: 62, title: '落梅风·烟寺晚钟' },
    { id: 63, title: '落梅风·平沙落雁' },
    { id: 64, title: '落梅风·江天暮雪' },
    { id: 65, title: '清江引·野兴' },
    { id: 66, title: '夜行船·秋思' },
    { id: 67, title: '乔木查·对景' },
    { id: 68, title: '拨不断·叹世' },
    { id: 69, title: '四块玉·恬退' },
    { id: 70, title: '庆东原·叹世' },
    { id: 71, title: '水仙子·咏江南' },
    { id: 72, title: '山坡羊·北邙山怀古' },
    { id: 73, title: '山坡羊·洛阳怀古' },
    { id: 74, title: '红绣鞋·警世' },
    { id: 75, title: '朱履曲·警世' },
    { id: 76, title: '得胜令·四月一日喜雨' },
    { id: 77, title: '雁儿落兼得胜令' },
    { id: 78, title: '折桂令·中秋' },
    { id: 79, title: '清江引·咏秋' },
    { id: 80, title: '天净沙·湖上送别' }
  ],
  shijing: [
    { id: 1, title: '关雎' },
    { id: 2, title: '蒹葭' },
    { id: 3, title: '桃夭' },
    { id: 4, title: '氓' },
    { id: 5, title: '采薇' },
    { id: 6, title: '鹿鸣' },
    { id: 7, title: '静女' },
    { id: 8, title: '木瓜' },
    { id: 9, title: '硕鼠' },
    { id: 10, title: '伐檀' },
    { id: 11, title: '子衿' },
    { id: 12, title: '击鼓' },
    { id: 13, title: '无衣' },
    { id: 14, title: '月出' },
    { id: 15, title: '汉广' },
    { id: 16, title: '芣苢' },
    { id: 17, title: '卷耳' },
    { id: 18, title: '摽有梅' },
    { id: 19, title: '柏舟' },
    { id: 20, title: '绿衣' },
    { id: 21, title: '黍离' },
    { id: 22, title: '伯兮' },
    { id: 23, title: '风雨' },
    { id: 24, title: '绸缪' },
    { id: 25, title: '东山' },
    { id: 26, title: '君子于役' },
    { id: 27, title: '君子阳阳' },
    { id: 28, title: '扬之水' },
    { id: 29, title: '葛藟' },
    { id: 30, title: '溱洧' },
    { id: 31, title: '女曰鸡鸣' },
    { id: 32, title: '狡童' },
    { id: 33, title: '出其东门' },
    { id: 34, title: '野有蔓草' },
    { id: 35, title: '蒹葭' },
    { id: 36, title: '黄鸟' },
    { id: 37, title: '七月' },
    { id: 38, title: '鸱鸮' },
    { id: 39, title: '破斧' },
    { id: 40, title: '伐柯' },
    { id: 41, title: '鹤鸣' },
    { id: 42, title: '白驹' },
    { id: 43, title: '蓼莪' },
    { id: 44, title: '常棣' },
    { id: 45, title: '文王' },
    { id: 46, title: '大明' },
    { id: 47, title: '绵' },
    { id: 48, title: '生民' },
    { id: 49, title: '清庙' },
    { id: 50, title: '维天之命' },
    { id: 51, title: '关雎' },
    { id: 52, title: '葛覃' },
    { id: 53, title: '卷耳' },
    { id: 54, title: '樛木' },
    { id: 55, title: '螽斯' },
    { id: 56, title: '桃夭' },
    { id: 57, title: '兔罝' },
    { id: 58, title: '芣苢' },
    { id: 59, title: '汉广' },
    { id: 60, title: '汝坟' },
    { id: 61, title: '麟之趾' },
    { id: 62, title: '鹊巢' },
    { id: 63, title: '采蘩' },
    { id: 64, title: '草虫' },
    { id: 65, title: '采蘋' },
    { id: 66, title: '甘棠' },
    { id: 67, title: '行露' },
    { id: 68, title: '羔羊' },
    { id: 69, title: '殷其雷' },
    { id: 70, title: '摽有梅' },
    { id: 71, title: '小星' },
    { id: 72, title: '江有汜' },
    { id: 73, title: '野有死麇' },
    { id: 74, title: '何彼秾矣' },
    { id: 75, title: '驺虞' }
  ],
  chuci: [
    { id: 1, title: '离骚' },
    { id: 2, title: '九歌·湘夫人' },
    { id: 3, title: '九歌·山鬼' },
    { id: 4, title: '天问' },
    { id: 5, title: '九歌·国殇' },
    { id: 6, title: '九歌·东君' },
    { id: 7, title: '九章·橘颂' },
    { id: 8, title: '招魂' },
    { id: 9, title: '九歌·湘君' },
    { id: 10, title: '九歌·河伯' },
    { id: 11, title: '九章·涉江' },
    { id: 12, title: '卜居' },
    { id: 13, title: '九歌·大司命' },
    { id: 14, title: '九歌·少司命' },
    { id: 15, title: '九章·哀郢' },
    { id: 16, title: '远游' },
    { id: 17, title: '渔父' },
    { id: 18, title: '招隐士' },
    { id: 19, title: '七谏·初放' },
    { id: 20, title: '九叹·逢纷' },
    { id: 21, title: '九歌·云中君' },
    { id: 22, title: '九歌·湘君' },
    { id: 23, title: '九歌·礼魂' },
    { id: 24, title: '九章·抽思' },
    { id: 25, title: '九章·思美人' },
    { id: 26, title: '九辩' },
    { id: 27, title: '风赋' },
    { id: 28, title: '高唐赋' },
    { id: 29, title: '神女赋' },
    { id: 30, title: '登徒子好色赋' },
    { id: 31, title: '对楚王问' },
    { id: 32, title: '吊屈原赋' },
    { id: 33, title: '鵩鸟赋' },
    { id: 34, title: '七谏·沉江' },
    { id: 35, title: '九怀·通路' },
    { id: 36, title: '九思·逢尤' },
    { id: 37, title: '哀时命' },
    { id: 38, title: '九怀·匡机' },
    { id: 39, title: '九叹·远逝' },
    { id: 40, title: '九思·伤时' },
    { id: 41, title: '九怀·危俊' },
    { id: 42, title: '九叹·惜贤' },
    { id: 43, title: '九思·守志' },
    { id: 44, title: '九怀·昭世' },
    { id: 45, title: '九叹·愍命' },
    { id: 46, title: '九思·疾世' },
    { id: 47, title: '九怀·桐柏' },
    { id: 48, title: '九叹·思古' },
    { id: 49, title: '九思·遭厄' },
    { id: 50, title: '九怀·蓄英' },
    { id: 51, title: '离骚·节选一' },
    { id: 52, title: '离骚·节选二' },
    { id: 53, title: '离骚·节选三' },
    { id: 54, title: '离骚·节选四' },
    { id: 55, title: '离骚·节选五' },
    { id: 56, title: '九歌·东皇太一' },
    { id: 57, title: '九歌·云中君' },
    { id: 58, title: '九歌·湘君' },
    { id: 59, title: '九歌·湘夫人' },
    { id: 60, title: '九歌·大司命' },
    { id: 61, title: '九歌·少司命' },
    { id: 62, title: '九歌·东君' },
    { id: 63, title: '九歌·河伯' },
    { id: 64, title: '九歌·山鬼' },
    { id: 65, title: '九歌·国殇' },
    { id: 66, title: '九歌·礼魂' },
    { id: 67, title: '天问·节选一' },
    { id: 68, title: '九章·涉江' },
    { id: 69, title: '九章·哀郢' },
    { id: 70, title: '卜居' }
  ],
  hanweishi: [
    { id: 1, title: '短歌行' },
    { id: 2, title: '观沧海' },
    { id: 3, title: '龟虽寿' },
    { id: 4, title: '蒿里行' },
    { id: 5, title: '燕歌行' },
    { id: 6, title: '白马篇' },
    { id: 7, title: '七步诗' },
    { id: 8, title: '洛神赋' },
    { id: 9, title: '饮马长城窟行' },
    { id: 10, title: '古诗十九首·行行重行行' },
    { id: 11, title: '长歌行' },
    { id: 12, title: '迢迢牵牛星' },
    { id: 13, title: '明月何皎皎' },
    { id: 14, title: '西北有高楼' },
    { id: 15, title: '涉江采芙蓉' },
    { id: 16, title: '苦寒行' },
    { id: 17, title: '美女篇' },
    { id: 18, title: '杂诗·南国有佳人' },
    { id: 19, title: '送应氏' },
    { id: 20, title: '赠白马王彪' },
    { id: 21, title: '七哀诗' },
    { id: 22, title: '登楼赋' },
    { id: 23, title: '咏史' },
    { id: 24, title: '秋胡行' },
    { id: 25, title: '古诗十九首·青青河畔草' },
    { id: 26, title: '古诗十九首·青青陵上柏' },
    { id: 27, title: '古诗十九首·今日良宴会' },
    { id: 28, title: '古诗十九首·明月皎夜光' },
    { id: 29, title: '古诗十九首·冉冉孤生竹' },
    { id: 30, title: '古诗十九首·庭中有奇树' },
    { id: 31, title: '古诗十九首·回车驾言迈' },
    { id: 32, title: '古诗十九首·东城高且长' },
    { id: 33, title: '古诗十九首·驱车上东门' },
    { id: 34, title: '古诗十九首·去者日以疏' },
    { id: 35, title: '古诗十九首·生年不满百' },
    { id: 36, title: '古诗十九首·凛凛岁云暮' },
    { id: 37, title: '古诗十九首·孟冬寒气至' },
    { id: 38, title: '古诗十九首·客从远方来' },
    { id: 39, title: '燕歌行·别日何易会日难' },
    { id: 40, title: '杂诗·西北有浮云' },
    { id: 41, title: '咏怀诗·夜中不能寐' },
    { id: 42, title: '咏怀诗·嘉树下成蹊' },
    { id: 43, title: '赠秀才入军' },
    { id: 44, title: '幽愤诗' },
    { id: 45, title: '悼亡诗' },
    { id: 46, title: '咏史·弱冠弄柔翰' },
    { id: 47, title: '咏史·郁郁涧底松' },
    { id: 48, title: '拟行行重行行' },
    { id: 49, title: '扶风歌' },
    { id: 50, title: '游仙诗' },
    { id: 51, title: '蒿里行' },
    { id: 52, title: '步出夏门行·冬十月' },
    { id: 53, title: '步出夏门行·河朔寒' },
    { id: 54, title: '步出夏门行·神龟虽寿' },
    { id: 55, title: '短歌行·其二' },
    { id: 56, title: '善哉行·其一' },
    { id: 57, title: '燕歌行·其二' },
    { id: 58, title: '燕歌行·其三' },
    { id: 59, title: '大墙上蒿行' },
    { id: 60, title: '杂诗·其一' },
    { id: 61, title: '杂诗·其二' },
    { id: 62, title: '清河作诗' },
    { id: 63, title: '黎阳作诗' },
    { id: 64, title: '送应氏·其一' },
    { id: 65, title: '送应氏·其二' },
    { id: 66, title: '杂诗·其一' },
    { id: 67, title: '杂诗·其二' },
    { id: 68, title: '杂诗·其三' },
    { id: 69, title: '杂诗·其四' },
    { id: 70, title: '杂诗·其五' },
    { id: 71, title: '杂诗·其六' },
    { id: 72, title: '七哀诗' },
    { id: 73, title: '情诗' },
    { id: 74, title: '朔风诗' },
    { id: 75, title: '白马篇' },
    { id: 76, title: '名都篇' },
    { id: 77, title: '美女篇' },
    { id: 78, title: '吁嗟篇' },
    { id: 79, title: '饮酒·其五' },
    { id: 80, title: '归园田居·其一' }
  ],
  yuefu: [
    { id: 1, title: '孔雀东南飞' },
    { id: 2, title: '木兰诗' },
    { id: 3, title: '陌上桑' },
    { id: 4, title: '长歌行' },
    { id: 5, title: '江南' },
    { id: 6, title: '上邪' },
    { id: 7, title: '有所思' },
    { id: 8, title: '饮马长城窟行' },
    { id: 9, title: '十五从军征' },
    { id: 10, title: '战城南' },
    { id: 11, title: '平陵东' },
    { id: 12, title: '东门行' },
    { id: 13, title: '孤儿行' },
    { id: 14, title: '病妇行' },
    { id: 15, title: '白头吟' },
    { id: 16, title: '雉子班' },
    { id: 17, title: '圣人出' },
    { id: 18, title: '邪径过空庐' },
    { id: 19, title: '巫山高' },
    { id: 20, title: '上陵' },
    { id: 21, title: '相逢行' },
    { id: 22, title: '陇西行' },
    { id: 23, title: '梁甫吟' },
    { id: 24, title: '幽兰操' },
    { id: 25, title: '将进酒' },
    { id: 26, title: '君马黄' },
    { id: 27, title: '芳树' },
    { id: 28, title: '鼓吹曲' },
    { id: 29, title: '薤露' },
    { id: 30, title: '蒿里' },
    { id: 31, title: '鸡鸣' },
    { id: 32, title: '平陵曲' },
    { id: 33, title: '陌上歌' },
    { id: 34, title: '长歌续短歌' },
    { id: 35, title: '君子行' },
    { id: 36, title: '猛虎行' },
    { id: 37, title: '相逢狭路间' },
    { id: 38, title: '长安有狭斜行' },
    { id: 39, title: '饮马行' },
    { id: 40, title: '青青河畔草' },
    { id: 41, title: '关雎' },
    { id: 42, title: '蒹葭' },
    { id: 43, title: '桃夭' },
    { id: 44, title: '氓' },
    { id: 45, title: '采薇' },
    { id: 46, title: '鹿鸣' },
    { id: 47, title: '静女' },
    { id: 48, title: '木瓜' },
    { id: 49, title: '硕鼠' },
    { id: 50, title: '伐檀' },
    { id: 51, title: '长歌行' },
    { id: 52, title: '君子行' },
    { id: 53, title: '相逢行' },
    { id: 54, title: '善哉行' },
    { id: 55, title: '西门行' },
    { id: 56, title: '东门行' },
    { id: 57, title: '妇病行' },
    { id: 58, title: '孤儿行' },
    { id: 59, title: '雁门太守行' },
    { id: 60, title: '战城南' },
    { id: 61, title: '巫山高' },
    { id: 62, title: '有所思' },
    { id: 63, title: '上邪' },
    { id: 64, title: '江南' },
    { id: 65, title: '鸡鸣' },
    { id: 66, title: '乌生' },
    { id: 67, title: '平陵东' },
    { id: 68, title: '陌上桑' },
    { id: 69, title: '长歌行·其二' },
    { id: 70, title: '猛虎行' },
    { id: 71, title: '枯鱼过河泣' },
    { id: 72, title: '饮马长城窟行' },
    { id: 73, title: '十五从军征' },
    { id: 74, title: '步出夏门行' },
    { id: 75, title: '李陵歌' },
    { id: 76, title: '北方有佳人' },
    { id: 77, title: '怨歌行' },
    { id: 78, title: '四愁诗' },
    { id: 79, title: '孔雀东南飞' },
    { id: 80, title: '木兰辞' }
  ],
  nanbeichao: [
    { id: 1, title: '登池上楼' },
    { id: 2, title: '山居赋' },
    { id: 3, title: '石壁精舍还湖中作' },
    { id: 4, title: '夜宿桐柏山' },
    { id: 5, title: '入彭蠡湖口' },
    { id: 6, title: '过始宁墅' },
    { id: 7, title: '从斤竹涧越岭溪行' },
    { id: 8, title: '晚出西射堂' },
    { id: 9, title: '登江中孤屿' },
    { id: 10, title: '初去郡' },
    { id: 11, title: '拟行路难·其一' },
    { id: 12, title: '拟行路难·其六' },
    { id: 13, title: '梅花落' },
    { id: 14, title: '代出自蓟北门行' },
    { id: 15, title: '赠故人' },
    { id: 16, title: '咏史' },
    { id: 17, title: '芜城赋' },
    { id: 18, title: '登黄鹤矶' },
    { id: 19, title: '日落望江赠荀丞' },
    { id: 20, title: '玩月城西门廨中' },
    { id: 21, title: '归园田居·其一' },
    { id: 22, title: '归园田居·其三' },
    { id: 23, title: '饮酒·其五' },
    { id: 24, title: '桃花源记' },
    { id: 25, title: '五柳先生传' },
    { id: 26, title: '归去来兮辞' },
    { id: 27, title: '咏荆轲' },
    { id: 28, title: '读山海经·其一' },
    { id: 29, title: '杂诗·其一' },
    { id: 30, title: '移居·其一' },
    { id: 31, title: '木兰诗' },
    { id: 32, title: '敕勒歌' },
    { id: 33, title: '陇头歌辞' },
    { id: 34, title: '折杨柳歌辞' },
    { id: 35, title: '琅琊王歌辞' },
    { id: 36, title: '地驱歌乐辞' },
    { id: 37, title: '雀劳利歌辞' },
    { id: 38, title: '慕容家自鲁企由谷歌' },
    { id: 39, title: '捉搦歌' },
    { id: 40, title: '河中之水歌' },
    { id: 41, title: '春别诗四首·其一' },
    { id: 42, title: '玉树后庭花' },
    { id: 43, title: '乌栖曲' },
    { id: 44, title: '咏内人昼眠' },
    { id: 45, title: '春江花月夜' },
    { id: 46, title: '三妇艳词' },
    { id: 47, title: '采莲曲' },
    { id: 48, title: '棹歌行' },
    { id: 49, title: '大堤曲' },
    { id: 50, title: '浴女诗' },
    { id: 51, title: '登池上楼' },
    { id: 52, title: '石壁精舍还湖中作' },
    { id: 53, title: '七里濑' },
    { id: 54, title: '登江中孤屿' },
    { id: 55, title: '夜宿石门诗' },
    { id: 56, title: '晚登三山还望京邑' },
    { id: 57, title: '之宣城郡出新林浦向板桥' },
    { id: 58, title: '游东田' },
    { id: 59, title: '玉阶怨' },
    { id: 60, title: '王孙游' },
    { id: 61, title: '入若耶溪' },
    { id: 62, title: '临高台' },
    { id: 63, title: '巫山高' },
    { id: 64, title: '别范安成' },
    { id: 65, title: '伤谢朓' },
    { id: 66, title: '咏芙蓉' },
    { id: 67, title: '拟行路难·其三' },
    { id: 68, title: '拟行路难·其四' },
    { id: 69, title: '拟行路难·其六' },
    { id: 70, title: '代出自蓟北门行' },
    { id: 71, title: '代东武吟' },
    { id: 72, title: '咏史' },
    { id: 73, title: '赠傅都曹别' },
    { id: 74, title: '北山移文' },
    { id: 75, title: '与朱元思书' }
  ],
  wudai: [
    { id: 1, title: '虞美人·春花秋月何时了' },
    { id: 2, title: '浪淘沙·帘外雨潺潺' },
    { id: 3, title: '相见欢·无言独上西楼' },
    { id: 4, title: '相见欢·林花谢了春红' },
    { id: 5, title: '乌夜啼·昨夜风兼雨' },
    { id: 6, title: '子夜歌·人生愁恨何能免' },
    { id: 7, title: '望江南·多少恨' },
    { id: 8, title: '望江南·多少泪' },
    { id: 9, title: '清平乐·别来春半' },
    { id: 10, title: '采桑子·亭前春逐红英尽' },
    { id: 11, title: '菩萨蛮·花明月暗笼轻雾' },
    { id: 12, title: '菩萨蛮·蓬莱院闭天台女' },
    { id: 13, title: '菩萨蛮·铜簧韵脆锵寒竹' },
    { id: 14, title: '阮郎归·呈郑王十二弟' },
    { id: 15, title: '捣练子令·深院静' },
    { id: 16, title: '捣练子令·云鬓乱' },
    { id: 17, title: '浣溪沙·红日已高三丈透' },
    { id: 18, title: '玉楼春·晚妆初了明肌雪' },
    { id: 19, title: '一斛珠·晓妆初过' },
    { id: 20, title: '临江仙·樱桃落尽春归去' },
    { id: 21, title: '鹊踏枝·谁道闲情抛掷久' },
    { id: 22, title: '鹊踏枝·几日行云何处去' },
    { id: 23, title: '鹊踏枝·庭院深深深几许' },
    { id: 24, title: '采桑子·花前失却游春侣' },
    { id: 25, title: '采桑子·笙歌放散人归去' },
    { id: 26, title: '谒金门·风乍起' },
    { id: 27, title: '谒金门·杨柳陌' },
    { id: 28, title: '清平乐·雨晴烟晚' },
    { id: 29, title: '清平乐·西园春早' },
    { id: 30, title: '醉桃源·南园春半踏青时' },
    { id: 31, title: '浣溪沙·五两竿头风欲平' },
    { id: 32, title: '江城子·竹里风生月上门' },
    { id: 33, title: '临江仙·海棠香老春江晚' },
    { id: 34, title: '菩萨蛮·越梅半拆轻寒里' },
    { id: 35, title: '菩萨蛮·含峰帽底纤腰袅' },
    { id: 36, title: '渔歌子·西塞山前白鹭飞' },
    { id: 37, title: '渔歌子·钓台渔父褐为裘' },
    { id: 38, title: '渔歌子·霅溪湾里钓鱼翁' },
    { id: 39, title: '潇湘神·斑竹枝' },
    { id: 40, title: '潇湘神·湘水流' },
    { id: 41, title: '梦江南·兰烬落' },
    { id: 42, title: '梦江南·楼上寝' },
    { id: 43, title: '采莲子·菡萏香连十顷陂' },
    { id: 44, title: '采莲子·船动湖光滟滟秋' },
    { id: 45, title: '忆江南·江南好' },
    { id: 46, title: '忆江南·江南忆' },
    { id: 47, title: '长相思·汴水流' },
    { id: 48, title: '长相思·深画眉' },
    { id: 49, title: '更漏子·玉炉香' },
    { id: 50, title: '更漏子·金雀钗' },
    { id: 51, title: '虞美人·春花秋月何时了' },
    { id: 52, title: '浪淘沙令·帘外雨潺潺' },
    { id: 53, title: '相见欢·无言独上西楼' },
    { id: 54, title: '相见欢·林花谢了春红' },
    { id: 55, title: '清平乐·别来春半' },
    { id: 56, title: '忆江南·多少恨' },
    { id: 57, title: '忆江南·多少泪' },
    { id: 58, title: '子夜歌·人生愁恨何能了' },
    { id: 59, title: '捣练子令·深院静' },
    { id: 60, title: '采桑子·辘轳金井梧桐晚' },
    { id: 61, title: '菩萨蛮·花明月暗笼轻雾' },
    { id: 62, title: '鹊踏枝·谁道闲情抛掷久' },
    { id: 63, title: '谒金门·风乍起' },
    { id: 64, title: '采桑子·群芳过后西湖好' },
    { id: 65, title: '醉花间·晴雪小园春未到' }
  ],
  mingqingshi: [
    { id: 1, title: '石灰吟' },
    { id: 2, title: '咏煤炭' },
    { id: 3, title: '过零丁洋' },
    { id: 4, title: '正气歌' },
    { id: 5, title: '金陵驿' },
    { id: 6, title: '满江红·怒发冲冠' },
    { id: 7, title: '满江红·登黄鹤楼有感' },
    { id: 8, title: '小重山·昨夜寒蛩不住鸣' },
    { id: 9, title: '游山西村' },
    { id: 10, title: '书愤' },
    { id: 11, title: '示儿' },
    { id: 12, title: '秋夜将晓出篱门迎凉有感' },
    { id: 13, title: '十一月四日风雨大作' },
    { id: 14, title: '金错刀行' },
    { id: 15, title: '关山月' },
    { id: 16, title: '卜算子·咏梅' },
    { id: 17, title: '钗头凤·红酥手' },
    { id: 18, title: '青玉案·元夕' },
    { id: 19, title: '破阵子·为陈同甫赋壮词以寄之' },
    { id: 20, title: '永遇乐·京口北固亭怀古' },
    { id: 21, title: '桃花庵歌' },
    { id: 22, title: '把酒对月歌' },
    { id: 23, title: '言志' },
    { id: 24, title: '画鸡' },
    { id: 25, title: '咏鸡诗' },
    { id: 26, title: '落花诗' },
    { id: 27, title: '题画竹' },
    { id: 28, title: '竹石' },
    { id: 29, title: '潍县署中画竹呈年伯包大中丞括' },
    { id: 30, title: '予告归里画竹别潍县绅士民' },
    { id: 31, title: '沁园春·雪' },
    { id: 32, title: '沁园春·长沙' },
    { id: 33, title: '七律·长征' },
    { id: 34, title: '七律·人民解放军占领南京' },
    { id: 35, title: '水调歌头·游泳' },
    { id: 36, title: '蝶恋花·答李淑一' },
    { id: 37, title: '卜算子·咏梅' },
    { id: 38, title: '菩萨蛮·黄鹤楼' },
    { id: 39, title: '清平乐·六盘山' },
    { id: 40, title: '忆秦娥·娄山关' },
    { id: 41, title: '己亥杂诗·浩荡离愁白日斜' },
    { id: 42, title: '己亥杂诗·九州生气恃风雷' },
    { id: 43, title: '己亥杂诗·只筹一缆十夫多' },
    { id: 44, title: '咏史' },
    { id: 45, title: '夜坐' },
    { id: 46, title: '西郊落花歌' },
    { id: 47, title: '秋心三首·其一' },
    { id: 48, title: '赋得秋河' },
    { id: 49, title: '投宋于庭' },
    { id: 50, title: '自春徂秋偶有所触' },
    { id: 51, title: '登金陵雨花台望大江' },
    { id: 52, title: '梅花九首·其一' },
    { id: 53, title: '寻胡隐君' },
    { id: 54, title: '田家行' },
    { id: 55, title: '卖柑者言' },
    { id: 56, title: '题太公钓渭图' },
    { id: 57, title: '北风行' },
    { id: 58, title: '马上作' },
    { id: 59, title: '韬钤深处' },
    { id: 60, title: '临江仙·滚滚长江东逝水' },
    { id: 61, title: '西江月·道德三皇五帝' },
    { id: 62, title: '三岔驿' },
    { id: 63, title: '寄答张孟威' },
    { id: 64, title: '秦淮海祠' },
    { id: 65, title: '五人墓碑记' },
    { id: 66, title: '秋日杂诗' },
    { id: 67, title: '马上口号' },
    { id: 68, title: '石灰吟' },
    { id: 69, title: '入塞' },
    { id: 70, title: '咏煤炭' },
    { id: 71, title: '己亥杂诗·其一二五' },
    { id: 72, title: '己亥杂诗·其五' },
    { id: 73, title: '己亥杂诗·其二二零' },
    { id: 74, title: '秋兴' },
    { id: 75, title: '杂感' },
    { id: 76, title: '绮怀十六首·其十五' },
    { id: 77, title: '别老母' },
    { id: 78, title: '苔' },
    { id: 79, title: '马嵬' },
    { id: 80, title: '寒夜' },
    { id: 81, title: '论诗五首·其二' },
    { id: 82, title: '秋柳四首·其一' },
    { id: 83, title: '真州绝句' },
    { id: 84, title: '题秋江独钓图' },
    { id: 85, title: '浣溪沙·谁念西风独自凉' }
  ]
}

const category = ref('')
const currentId = ref(0)
const isClient = ref(false)

onMounted(() => {
  isClient.value = true
  const currentPath = window.location.pathname
  const match = currentPath.match(/\/shici\/([^/]+)\/(\d+)\.html?/)
  if (match) {
    category.value = match[1]
    currentId.value = parseInt(match[2])
  }
})

const poems = computed(() => poemLists[category.value] || [])

const currentIndex = computed(() => {
  if (!isClient.value) return -1
  return poems.value.findIndex(p => p.id === currentId.value)
})

const prevPoem = computed(() => {
  if (!isClient.value) return null
  const idx = currentIndex.value
  if (idx > 0) {
    return poems.value[idx - 1]
  }
  return null
})

const nextPoem = computed(() => {
  if (!isClient.value) return null
  const idx = currentIndex.value
  if (idx >= 0 && idx < poems.value.length - 1) {
    return poems.value[idx + 1]
  }
  return null
})

const prevLink = computed(() => {
  if (!prevPoem.value) return ''
  return `/shici/${category.value}/${prevPoem.value.id}.html`
})

const nextLink = computed(() => {
  if (!nextPoem.value) return ''
  return `/shici/${category.value}/${nextPoem.value.id}.html`
})
</script>

<style scoped>
.poem-nav {
  display: flex;
  justify-content: space-between;
  align-items: stretch;
  margin-top: 48px;
  padding-top: 24px;
  border-top: 1px solid var(--vp-c-divider, rgba(133, 102, 46, 0.15));
  gap: 16px;
}

.prev-poem,
.next-poem {
  display: flex;
  flex-direction: column;
  padding: 16px 20px;
  border-radius: 8px;
  text-decoration: none;
  transition: all 0.3s ease;
  background: var(--vp-c-brand-soft, rgba(133, 102, 46, 0.12));
  border: 1px solid var(--vp-c-brand-3, rgba(133, 102, 46, 0.2));
  max-width: 48%;
  flex: 1;
}

.prev-poem {
  align-items: flex-start;
}

.next-poem {
  align-items: flex-end;
  text-align: right;
}

.prev-poem:hover,
.next-poem:hover {
  background: var(--vp-c-brand-3, #ad8e56);
  border-color: var(--vp-c-brand-3, #ad8e56);
}

.prev-poem:hover .nav-label,
.prev-poem:hover .nav-title,
.next-poem:hover .nav-label,
.next-poem:hover .nav-title {
  color: #fff;
}

.nav-label {
  font-size: 13px;
  color: var(--vp-c-text-3, #999);
  margin-bottom: 4px;
  transition: color 0.3s ease;
}

.nav-title {
  font-size: 15px;
  font-weight: 600;
  color: var(--vp-c-brand-1, #85662e);
  transition: color 0.3s ease;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 100%;
}

.nav-placeholder {
  flex: 1;
  max-width: 48%;
}

@media (max-width: 640px) {
  .poem-nav {
    flex-direction: column;
    gap: 12px;
  }

  .prev-poem,
  .next-poem,
  .nav-placeholder {
    max-width: 100%;
    width: 100%;
    box-sizing: border-box;
  }

  .next-poem {
    align-items: flex-start;
    text-align: left;
  }
}
</style>
